{% set name = "toastedmarshmallow" %}
{% set version = "2.15.2.post1" %}
{% set sha256 = "aad7c89720a27d6362e1362394ceaedf5e1648aba4506c1971da35b3642810e9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - attrs >=17.1.0
    - six

test:
  imports:
    - marshmallow
    - toastedmarshmallow

about:
  home: https://github.com/lyft/toasted-marshmallow
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'A JIT implementation for Marshmallow to speed up dumping and loading objects.'

  description: |
    Toasted Marshmallow implements a JIT for marshmallow that speeds up 
    dumping objects 10-25X (depending on your schema). Toasted Marshmallow 
    allows you to have the great API that Marshmallow provides without having 
    to sacrifice performance!
  dev_url: https://github.com/lyft/toasted-marshmallow

extra:
  recipe-maintainers:
    - synapticarbors
