travis:
  secure:
    BINSTAR_TOKEN: nx6+cqvBwMIVgpxlYu4Ux+dH6PS0m2y2EA/QF+fiYiPg4udS+dZLvErka4V/Fv+hOsxgIODU/SLil2pWX3+X76o06KebzG8uA8TRQueDwrzu31DAe2nOs2BexNuUsZnvxVZvxn3B49u19eEdngL9QiNE8My0HSVgZTwQPbyufc4LRhHBTop9pPXNhzhATEg2y9RHJlGEA5zYqhyYo42oKFiHby2gp+KNZaJtVzM5RV7pOl0IILb78E0HP7GI6MTxNKaBihg/H/gzYA/20djge+QJg8mj8VU+5nrU6O4SQ80GD6lKWzgXqQKiG4KRq7csWLRN+k11il4tGF9VIbgCv0lrqDzjfQChY3LTkoXIxTggt4VrT65ZPvEJEGNVccg659uzj6PPRxCrn/ZWqeSDn3lLNWxrD0XsP8zQTBstD8ggF1QVJHsC5iPoUmkHDqao2gqVneSCkia0/b73IKUKscD8N9v4E8yxMFdFAjwdKSH2lAsNq/J+2F/3tMCWs0w+oDanPgUzRNED4yNa9W00FAkqzXiDa77RgJGCk4oU4jI1NucFKJbn3z6kKU5m36G55s2eMoLehhAjSLXAsfcjz2/7UeEq3kakm9Xt9LIhrN5vCpJT3eBOjfan4ery6TlzK6t2nN6IkXDQp9/BZg+r9ARJ0H9nzSoIQ2oYmErLjnk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
