travis:
  secure:
    BINSTAR_TOKEN: ojYQm1cFSmdYLpsI/Z47d1jSusBPhLdfhZpKyf+q5JLxbTUd2Ety916Cy1gg7ObjjvGXcbGkC/53Ua8P9VOCoR5o03MBAIB815XhHp3lfROtHNdaDTL0tg6mhU+zIF74DD3QTQbqF1qXwjCDgSAqDWN1yLgfqxSkki43mkTFcZuk3y+AanYRiaMbE5D/g1R/ARdr3hVWdePfLVfY1s8QiOQsXKecHYoHaTl+/P6weF2IXrS+ZClGXiJYAZLI0MfN+2GIy1rZv0rKILJKqMyl9Xd3nvfvCntslk5bUN5dX4QR1K+Vgni7V+ziLJlc4u2KGYiQgTDBeELdJFdC6pOiVrHEWvY/26xk8mrAJ/f9OYVqFl6qxkZq/xh3oVvqK98r/V49wL7D0Id3ctiib96HmFGvrp2smfquUT911rXH8+HxolQxtU2TBjzb74nC/FCDqgPJSYjIvSeOarq7nlSy16qGhYW/vE5C88DSn4c1euScSWgUlF9Gc2NRzL9IrZHSLBXzYIkiaV7mSuVvAiuw0+sVDmztrGnKYw7AF0C1xF5iMOPodhsy+klaMV+7L2LcvYU1gbHnERUb9QZf4Y7FbSuD2Z5+AgsLWBFF6axNltSQa/kXP4XpwepSh9qTC8PoZC+YIhkVA44Q31JUPtXjOLIMy7p3innmC17HxrBTnsY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
