travis:
  secure:
    BINSTAR_TOKEN: BgGZxFq56l5Pc/ZrepJeeBGd/QG5u9PQOmmbo6Wq2gb97NirjmYlE8rUatJbAPBYgStxtdDlaaE0HnDWVlJm7q2QFCLmz48AIWGqYCZxXHTnsyxMT51uGrOq3UYvMqRXjroWAxsQFF7NX8/owPJSf9KeDV+9PkpSkU3Why3f9NWz2HEihAAGUNofLrNs+qUxtilAwWgu/RyTEd5rQpDCQGesjc6GJYgUltHNmZ67vexwiZj5qFDFYGaAXub1DChxFE9KE0gU8HmiWFYBzvLE7vWI79bPXHGAeBNFH7e3FdWj0zc7U6sIzXq4y3/FIQ807LMh/iBmfQROH8XquQdn9A9JARvGVgK0wpoGIyET00jLva3AWDYsooDzzqxbTtm65N7m7ccdSU5XaYLEBnqrn0x01Qs+sIgh+T/Iv8hx86dy8sezfz34yyUuIEbfTFSohUVqIOyya+ITUFBmOj1A+LcbFR8YGmEBte3ZH3kTT/Ji7iX/mDsnwNlcN/08iusoFTTvgEDtP7YSjasRkXXZ6ZpwIcHYDTZ8U/LvzyNFoQP13iWtPS3Ts3SuJDowh8K7vzdzJLuhnJY1Mk1bio3k+5mgkJ6ildNAPzubaq4PgM8/XFs8YB/4FDxoRiY8kvw+bPSWUTkxich1AxrkowOxW++9FJD8sNP4bVZ1bNuS2hQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
