travis:
  secure:
    BINSTAR_TOKEN: zXAyJLcTvQNfK8c7x8eO9obcW+/aUIJslqZCZt+M8DZRJk9W01yAw9tfU6WOMjFCbmfS/HFec1fd5Qm/z5WktmzPHw5Je3eVNNCp71LGR1bqkgTkwoLSjUZhqsMv4ISmxE+2yx/XV32YbGF6WK+QCXgwOuT2rflbAgux5U8X1+FWz16Y6fOscXpip/Qk3uv99QH9KnsV3dfSZmcUNcLHZ6RyrMRR2biw4YK3ViKx+0dGWw//e+ZalxwBazy0onAuavT5m7GiEUIo2QPFNHSRJ4jioaxd64KeDhnLqrXQ0mB3m20eKHBkZkPbYYyL533sSuQkACoCqUE9lp4X0M45VTUkeZlrcBEXcaASykHIH2zDZqL7TgJmgTvuzuJj0UbYywImwIzT8h5c70PD0pLK3RAGjo9rSkCGeLwffnFmPrqkp7akryw6vPqdizvrt4UD6siFBHDO6cRNZzMTleh5I+N/B3WJIMZknVvQGEAHMUgDG/CIeQcmn/4ReCIPmskBTQ4cPGainWBJxzMzFSa1mtSDUz9RZ1CfUXtFrucrGzIJjrPZ8k+Jo/HayjNyMEO2aCTDKkQOkzqMzZLgw2GF9v9bIfM5Co7ZM4iqcRSjUbwPL55rOcD+4ht5K5Gbiqzd67LWm6Orfx08MUBGB0SSsYiU2rVYH9IFOduHBw9kxqY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
